apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-project
  labels:
    app: demo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-project
  template:
    metadata:
      labels:
        app: demo-project
    spec:
      containers:
        - name: demo-project
          image: nizamsk/devops-integration:latest
          ports:
            - containerPort: 9001
