apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: devops-virtualservice
spec:
  hosts:
    - "*"  # Or use a real domain like devops.local
  gateways:
    - devops-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: devops-service
            port:
              number: 80
