apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: devops-gateway
spec:
  selector:
    istio: ingressgateway # use the default ingress gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
