apiVersion: v1
kind: Service
metadata:
  name: demo-project-service
  namespace: devops
spec:
  selector:
    app: demo-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001
  type: LoadBalancer
