apiVersion: v1
kind: Service
metadata:
  name: demo-project-service
  labels:
    app: demo-project
spec:
  selector:
    app: demo-project
  ports:
    - protocol: TCP
      port: 80        # External port exposed by service
      targetPort: 9001  # Port on the pod container
  type: LoadBalancer
